import os

print("Start get 3rd party golang modules")

os.system('go get github.com/deckarep/golang-set')
os.system('go get github.com/deckarep/golang-set')
os.system('go get github.com/rs/cors')
os.system('go get github.com/davecgh/go-spew/spew')
os.system('go get github.com/edsrzf/mmap-go')
os.system('go get github.com/hashicorp/golang-lru')
os.system('go get github.com/huin/goupnp')
os.system('go get github.com/jackpal/go-nat-pmp')
os.system('go get github.com/karalabe/usb')
os.system('go get github.com/olekukonko/tablewriter')
os.system('go get github.com/pborman/uuid')
os.system('go get github.com/prometheus/tsdb/fileutil')
os.system('go get github.com/rjeczalik/notify')
os.system('go get github.com/status-im/keycard-go/derivationpath')
os.system('go get github.com/syndtr/goleveldb/leveldb')
os.system('go get github.com/tyler-smith/go-bip39')
os.system('go get github.com/wsddn/go-ecdh')
os.system('go get golang.org/x/text/unicode/norm')
os.system('go get github.com/gballet/go-libpcsclite')
os.system('go get github.com/golang/protobuf/proto')
os.system('go get github.com/golang/protobuf/protoc-gen-go/descriptor')
os.system('go get github.com/gorilla/websocket')
os.system('go get github.com/dgrijalva/jwt-go')
os.system('go get github.com/go-sql-driver/mysql')
os.system('go get github.com/shopspring/decimal')